### ISSUE TITLE
Add escape attribute

### ISSUE THREAD

**Issue by cdarwin** [saltstack-formulas/mysql-formula#111] opened 2016-03-24 17:19 UTC
[`mysql_grants.present`](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.mysql_grants.html#salt.states.mysql_grants.present) supports a boolean attribute to override the default escaping of string values. The formula should support this as well.

See luciddg/mysql-formula#1

**Comment by evoWeb** [comment] 2017-12-15 21:37
I have copied the current user.sls in my local repository and tested it with the mentioned escape setting. Works as expected. When does this get merged? Would love to remove my file because it was only necessary for this change.

**Comment by aboe76** [comment] 2017-12-15 22:06
If there aren't any compatibility issues, or regressions then I will merge it.

**Closed** 2018-12-18 22:59 UTC
