### ISSUE TITLE
Failure Granting Permissions

### ISSUE THREAD

**Issue by getSurreal** [saltstack-formulas/mysql-formula#211] opened 2019-01-14 23:59 UTC
Pillar
```
mysql:
  database:
    - foo

  user:
    frank:
      password: 'somepass'
      host: localhost
      databases:
        - database: foo
          grants: ['select', 'insert', 'update']
          escape: True

```
State.Apply
```
root@devsalt:/srv/salt/pillar# salt 'devmysql' state.apply mysql.database
devmysql:
----------
          ID: mysql_python
    Function: pkg.installed
        Name: python-mysqldb
      Result: True
     Comment: All specified packages are already installed
     Started: 23:49:15.702920
    Duration: 587.005 ms
     Changes:
----------
          ID: mysql_db_0
    Function: mysql_database.present
        Name: foo
      Result: True
     Comment: The database foo has been created
     Started: 23:49:16.291445
    Duration: 4.758 ms
     Changes:
              ----------
              foo:
                  Present

Summary for devmysql
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time: 591.763 ms
root@devsalt:/srv/salt/pillar# salt 'devmysql' state.apply mysql.user
devmysql:
----------
          ID: mysql_python
    Function: pkg.installed
        Name: python-mysqldb
      Result: True
     Comment: All specified packages are already installed
     Started: 23:49:26.786735
    Duration: 608.699 ms
     Changes:
----------
          ID: mysql_user_frank_localhost
    Function: mysql_user.present
        Name: frank
      Result: True
     Comment: The user frank@localhost has been added
     Started: 23:49:27.396376
    Duration: 13.68 ms
     Changes:
              ----------
              frank:
                  Present
----------
          ID: mysql_user_frank_localhost_0
    Function: mysql_grants.present
        Name: frank_foo_all
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1913, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1898, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/mysql_grants.py", line 150, in present
                  grant, database, user, host, grant_option, escape, **connection_args
                File "/usr/lib/python3/dist-packages/salt/modules/mysql.py", line 1802, in grant_exists
                  grants = user_grants(user, host, **connection_args)
                File "/usr/lib/python3/dist-packages/salt/modules/mysql.py", line 1769, in user_grants
                  tmp = grant[0].split(' IDENTIFIED BY')[0]
              TypeError: a bytes-like object is required, not 'str'
     Started: 23:49:27.410972
    Duration: 6.576 ms
     Changes:

Summary for devmysql
------------
Succeeded: 2 (changed=1)
Failed:    1
------------
Total states run:     3
Total run time: 628.955 ms
ERROR: Minions returned with non-zero exit code
```
Salt Master
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-42-generic
         system: Linux
        version: Ubuntu 18.04 bionic

```

Salt Minion
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-42-generic
         system: Linux
        version: Ubuntu 18.04 bionic

```

**Comment by getSurreal** [comment] 2019-01-15 00:48
Looks like a Python3 compatibility issue.  I stood up a python2 master/minion and it worked.

**Comment by noelmcloughlin** [comment] 2019-01-15 12:44
Looks like a salt bug?
```
File "/usr/lib/python3/dist-packages/salt/modules/mysql.py", line 1769, in user_grants
                  tmp = grant[0].split(' IDENTIFIED BY')[0]
```

**Comment by stevengubler** [comment] 2020-08-26 22:12
Has there been any progress on this? I'm still getting this error.

**Comment by myii** [comment] 2020-08-26 22:16
@stevengubler What version of Salt are you running?  I believe this might have been part of the fixes released in `3000.1`:

* https://docs.saltstack.com/en/latest/topics/releases/3000.1.html

**Comment by stevengubler** [comment] 2020-08-26 23:59
@myii The environment I was seeing the error on was very out of date, like 2017 or something.

After upgrading salt, I can confirm that this issue is not present on the latest version of salt.

**Comment by myii** [comment] 2020-08-27 05:37
Thanks for confirming.  I reckon we can close this issue based on that.

**Closed by myii** 2020-08-27 05:37 UTC
