### ISSUE TITLE
Missing debconf-utils package

### ISSUE THREAD

**Issue by RickvdStaaij** [saltstack-formulas/mysql-formula#42] opened 2014-11-11 14:36 UTC
After I implemented the `mysql-formula`, my vagrant provision was failing. giving me the following error:

```
----------
          ID: mysql_debconf
    Function: debconf.set
        Name: mysql-server
      Result: False
     Comment: State debconf.set found in sls mysql.server is unavailable
     Changes:  
----------
```

After some research I found that the `debconf-utils` package was missing on the vagrant box. After doing a `sudo apt-get install debconf-utils` the provision was working fine again. I think this formula is missing a dependency to this package.

**Comment by noelmcloughlin** [comment] 2018-06-18 23:21
duplicate of #31

**Closed by noelmcloughlin** 2018-06-18 23:21 UTC
